## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "LetterPlace" );
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "LetterPlace", "doc" )[1]![1], "LetterPlace.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "LetterPlace" );
QUIT;
